# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca1b6aacde7c54ebc2b0b05ce8e7d45b32bd758ac8ab366b0036c8ecea99de2ed9503b4976702728f141e75bcd9146debb1986a02eb785ff354263aa1474860e

test:
  secret_key_base: 8807afc5b7fdfa59ec73050e4c2f828fa1e4bd224618d2c23dddc7ab13065ed963c315d873bbd48ff4728e3557378cec6a2bd790ab814a7f4bcfe2d46df0bbf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
